---
title: "multisemimarkov package"
author: "Yongho Lim"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
header-includes: 
  - \usepackage{tikz}
  - \usepackage{pgfplots}
  - \usepackage{pgf,tikz,pgfplots}
  - \pgfplotsset{compat=1.15}
  - \usepackage{mathrsfs}
  - \usetikzlibrary{arrows}
  - \usetikzlibrary{patterns}
  - \usetikzlibrary{positioning}
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# multisemimarkov

<!-- badges: start -->

<!-- badges: end -->

Provides functionality with Multistate semi-Markov model with masked causes

## Installation

You can install the development version of `multisemimarkov` like so:

``` r
install.packages("multisemimarkov")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(multisemimarkov)
## basic example code
```








